// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Athlete struct {
	ID                 uuid.UUID
	CoachID            uuid.UUID
	Name               string
	Email              pgtype.Text
	Tz                 string
	StravaAthleteID    pgtype.Int8
	StravaAccessToken  pgtype.Text
	StravaRefreshToken pgtype.Text
	StravaTokenExpiry  pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	LastStravaSync     pgtype.Timestamptz
}

type Coach struct {
	ID        uuid.UUID
	Email     string
	Name      pgtype.Text
	Tz        string
	CreatedAt pgtype.Timestamptz
}

type SessionStore struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type Workout struct {
	ID          uuid.UUID
	AthleteID   uuid.UUID
	Source      string
	SourceID    int64
	Name        pgtype.Text
	Sport       string
	StartedAt   pgtype.Timestamptz
	DurationSec int32
	DistanceM   pgtype.Float8
	ElevGainM   pgtype.Float8
	AvgHr       pgtype.Int4
	RawJson     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
