// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Coach struct {
	ID        pgtype.UUID
	Email     string
	Name      pgtype.Text
	Tz        string
	CreatedAt pgtype.Timestamptz
}

type SessionStore struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}
